name: Release mod to Modrinth

on: [ pull_request, workflow_dispatch ]

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:

      - name: checkout
        uses: actions/checkout@v3
        with:
          submodules: true


      - name: Get Property

        uses: christian-draeger/read-properties@1.1.1
        id: read_property
        with:
          path: './gradle.properties'
          properties: 'mod_version mod_name modrinth_id'



      - name: check env
        run: env



      - name: setup Java
        uses: actions/setup-java@v2
        with:
          distribution: "temurin"
          java-version: 17

      - name: make Gradle Wrapper executable
        if: ${{ runner.os != 'Windows' }}
        run: chmod +x ./gradlew

      - name: build
        run: ./gradlew clean build

      - name: release to Modrinth
        uses: Kir-Antipov/mc-publish@v3.3
        with:
          modrinth-id: "${{ steps.read-property.outputs.modrinth_id }}"
          modrinth-token: "${{ secrets.PUBLISH_MODRINTH_TOKEN }}"

          version-type: release
          changelog-file: CHANGELOG.md

          loaders: fabric
          java: 17

          name: "${{ steps.read-property.outputs.mod_name }} v${{ steps.read-property.outputs.mod_version }}"
